name: zam_clipboard
version: 0.1.0
description: An interface or port for all clipboard services connected via adapters.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_clipboard
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_command_pattern: ^0.1.0
  zam_core: ^0.5.0

dev_dependencies:
  zam_test: ^0.3.0
